### ISSUE TITLE
【移动端】Swiper卡顿之路

### ISSUE THREAD

**Issue by mingttong** [mingttong/learning#41]
# 背景

在做项目的时候用到了Swiper轮播图，因为项目基于Vue，便使用了vue-awesome-swiper这个开源组件。但是在测试的过程中普遍反馈轮播图滑动卡顿，特别是在安卓机型上，IOS相对来说比较好。
### 现象
滑动轮播图卡片时卡顿，在IOS中卡顿不明显，但在安卓中（特别是性能比较差的机型），卡顿现象非常明显。
### 问题定位
通过debug，排查到轮播图在滚动过程中更新视图状态就会卡顿，起初认为是数据更新导致的页面卡顿，于是先给状态更新加上了个setTimeout
 
但是发现轮播图还是会卡，我又将代码改造了下，让所有轮播图的动画效果都结束后，再更新视图。结果现象更神奇，轮播图滚动完后等待了几百毫秒视图才更新，并且在此期间页面无法操作。
 
这很奇怪，我更新的数据只是一个简单的number，并没有很多依赖的操作，理论上不会有这么大的开销。于是我做了个实验，不通过滚动轮播图更新数据，将更新数据与轮播图分开。
 
每次点击按钮更新视图都很慢，耗时和滚动轮播图是差不多，在400毫秒左右，很诡异。。
更神奇的是dom变化，每次更新视图swiper内部一大半的slide节点都被销毁重新创建了
 
vue的diff出bug了？为何更新与轮播图无关的视图会把轮播图内部的组件销毁了

带着这个疑问我去查阅了vue-awesome-swiper和swiper的issue
 
 
 
 
这个问题只有在loop: true的情况下才会出现 
vue-awesome-swiper组件有个默认为true的参数autoUpdate，在swiper组件updated钩子中会根据autoUpdate判断是否要swiper自动更新，自动更新的一项内容就是销毁loop复制出来的slide并重新创建 。就是这个自动更新的机制导致页面数据更新耗时特别长

因为使用swiper时都会用插槽引用swiper-slide
 
而子组件使用插槽，父组件视图更新同样会触发子组件updated。这就导致了引用swiper组件时，即使更新与swiper组件无关的视图数据，也会触发swiper的updated，从而触发自动更新。

https://juejin.cn/post/6844904113432444942#heading-9（这里解释了为什么使用slot会更新子组件）
### 解决方案
有两个方案：
1.autoUpdate设置为false，让swiper不再自动销毁组件（仅限于轮播图数据不会更新）。注意：如果需要更新轮播图数据时需要手动更新组件，否则loop复制出来的slides不会更新 
 
2. 不在swiper的父组件中更新视图数据。在swiper上层再封装一个组件，仅用于轮播图展示及更新，其他需要更新视图的相关操作都放在该组件之外，以此来避免触发swiper的updated。
### 效果
因为项目中没有动态更改轮播图数据的需求，所以我采用了方案一，设置autoUpdate = false，目前非常顺滑
 

# IOS 14.5 14.6下Swiper卡顿
这个问题更是重量级的，我是在IOS14.6下，kwai APP的yoda容器里出现这个问题，从网上的issue反馈来看，IOS14.5 14.6的浏览器上都出现同样的问题
## 现象
这个问题也十分诡异，我们项目在测试过程中没有发现这个问题（在解了上一个卡顿问题后轮播图一直都非常顺畅），但是在内测的过程中有同学反馈在IOS上卡片滑动又卡顿了，在安卓上反而不卡（IOS性能比安卓还差？）

这是安卓下的丝滑效果
 
而在IOS下会出现滑动后一顿一顿的效果
 
## 问题定位
在经过多个机器测试后，我发现这个问题只在IOS14.6版本中能复现，那么能定位出这个问题是特殊系统版本的问题，基本排除了页面本身的性能问题。

swiper在touchmove拖动轮播图时并没有出现卡顿现象，只有在touchend后，轮播图自动滚动到目标位置的这个动画出现了卡顿，这一部分是用transition实现的过渡效果。难道在IOS14.6上transition失效了？我用margin + transition尝试了下，过渡效果正常，只有translate + transition过渡效果卡顿：
 

现在问题定位到了是IOS14.6下，transition + translate做动画会有卡顿问题 ，我查阅了下swiper的issue，在IOS14.5上也有人反馈出现滑动卡顿 的问题：
里面有位老哥提出用cssMode: true启用CSS Scroll Snap API，我尝试了下确实不会卡顿，但是开启这个api限制很多，比如无法loop，无法centeredSlides，显然这是不符合产品预期的：
 

另一个办法就是替换translate做过渡动画，我们不需要把swiper所有移动的效果都改写，只需要改写touchend后，轮播图自动滚动到目标位置 。有两个方案：
1. 使用margin替换动画效果。（否了） 
	a. 思路是在touchend后将swiper的偏移改成用margin实现，等动画效果完成后再改回成用translate做偏移（因为swiper内部很多计算都依赖translate，所以最终需要还原translate）
	b. 但经过尝试，这样做过渡动画swiper会先闪一下（translate被设置为0），然后又闪到目标位置（margin被设置成目标值），无法使用。
2. 使用requestAnimationFrame自己实现动画效果。在touchend后将swiper的transition取消，通过自己实现的动画做偏移。（采用） 

## 解决方案
劫持swiper的setTranslate事件，改写其过渡动画：
```html
<swiper
    :options="swiperCenterOptions"
    :auto-update="false"
    @set-translate="onSetTranslate"
>
    <swiper-slide
        v-for="item in list"
        :key="item"
    >
        <div class="swiper-item slide-inner" :style="`background:#aa${item}`">{{ item }}</div>
    </swiper-slide>
</swiper>
```

```javascript

methods: {
  	// 设置新的translate值
    onSetTranslate(swiper, targetTransVal) {
      	const speed = 300; // 替代transition-duration
        const wrapper = swiper.$wrapperEl[0]; // wrapper element
        // 当用transition设置动画效果时，此时劫持这部分动画
        if (wrapper.style.transitionDuration !== '0ms') {
            // 获取当前的translate值
            const curTransVal = this.swiper.getTranslate();
            // 取消transition动画
            wrapper.style.transitionDuration = '';
            wrapper.style.transform = `translate3d(${curTransVal}px, 0px, 0px)`;

            // 使用requestFrameAnimation实现过渡动画
            const transSimulator = getTransitionSimulator(wrapper, targetTransVal - curTransVal, speed, (el, val) => {
              	// 每一帧移动到的目标位置
                el.style.transform = `translate3d(${curTransVal + val}px, 0px, 0px)`;
            });
            await transSimulator();
            // 结束transition，调用回调（模拟swiper内部实现）
            swiper.onSlideToWrapperTransitionEnd.call(wrapper, { target: wrapper });

        }
    }
}
```

```javascript
getTransitionSimulator方法实现 
// 使用ease-out效果
function easeOut(currentTime, startValue, changeValue, duration) {
    currentTime /= duration;
    return -changeValue * currentTime * (currentTime - 2) + startValue;
}

/**
 * 实现过渡动画
 * @param {HTMLElement} ele 元素节点
 * @param {number} distance 移动总距离
 * @param {number} duration 动画持续时长
 * @param {Function} callback 每帧执行的操作
 */
function getTransitionSimulator(ele, distance, duration, callback) {
    let handle;
    let resolve;
    return () => {
        let promise = new Promise(res => {
            resolve = res;
        });
        let startTime = performance.now();
        cancelAnimationFrame(handle);
        function _animation() {
            let current = performance.now();
            // 每一帧移动的距离
            let disVal = easeOut(current - startTime, 0, distance, duration);

            callback(ele, disVal);
            if ((current - startTime) / duration < 1) {
                handle = requestAnimationFrame(_animation);
            } else {
                cancelAnimationFrame(handle);
                resolve();
            }
        }
        handle = requestAnimationFrame(_animation);
        return promise;
    };
}
```

**Comment by lsmsnail** [comment]
我也碰到了这个问题，用了你的方法，在浏览器中顺畅了，但是微信里打开还是卡的，请问有办法解决吗？

**Comment by mingttong** [comment]
> 我也碰到了这个问题，用了你的方法，在浏览器中顺畅了，但是微信里打开还是卡的，请问有办法解决吗？

@lsmsnail 你是遇到了性能卡顿问题（第一个）还是特殊ios机型下卡顿问题（第二个）

**Comment by lsmsnail** [comment]
特殊机型卡顿问题， IOS 14.5 14.6下Swiper卡顿

**Comment by mingttong** [comment]
你可以写个demo页面（页面没有其他内容，只有几个简单的元素），试试在微信里用requestAnimationFrame作过渡动画会不会卡，500毫秒移动个元素300px。也可以拿setTimeout(() => {}, 10) 去做。
